TrugoAdmin/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrugoAdmin.Models.DalClasses;
using TruGoClassLibrary.RequestModels;

namespace TrugoAdmin.Controllers
{
    public class InvoicesController : Controller
    {
        private InvoiceRequestClass _invoiceRequestClass;

        public InvoiceRequestClass InvoiceRequestClass
        {
            get
            {
                return new InvoiceRequestClass();
            }

            set
            {
                _invoiceRequestClass = value;
            }
        }

        public InvoicesController(InvoiceRequestClass invoiceRequestClass)
        {
            InvoiceRequestClass = invoiceRequestClass;
        }

        public InvoicesController()
        {

        }
        // GET: Invoices
        public ActionResult GetAllInvoices()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = InvoiceRequestClass.GetAllRequest();

            return View(requests);
        }

        public ActionResult PendingInvoices()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = InvoiceRequestClass.GetAllRequest().Where(m => m.Verified == false || m.AdminStatus == "not approved");
            
            return View(requests);
        }

        public ActionResult VerifiedInvoices()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = InvoiceRequestClass.GetAllRequest().Where(m => m.Verified == true);

            return View(requests);
        }

        public ActionResult ApprovedInvoices()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = InvoiceRequestClass.GetAllRequest().Where(m => m.Verified == true && m.AdminStatus == "approved");

            return View(requests);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApproveRequest(InvoiceRequestModel model)
        {
            var status = InvoiceRequestClass.ApproveRequest(model);

            if (status)
            {
                Session["msg"] = "Invoice request approved";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("ApprovedInvoices");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VerifyRequest(InvoiceRequestModel model)
        {
            var status = InvoiceRequestClass.VerifyRequest(model);

            if (status)
            {
                Session["msg"] = "Invoice request verified";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("VerifiedInvoices");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeclineRequest(InvoiceRequestModel model)
        {
            var status = InvoiceRequestClass.DeclineRequest(model);

            if (status)
            {
                Session["msg"] = "Invoice request declined";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("PendingInvoices");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RevokeVerifiedRequest(InvoiceRequestModel model)
        {
            var status = InvoiceRequestClass.RevokeVerifiedRequest(model);

            if (status)
            {
                Session["msg"] = "Invoice request revoked";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("GetAllInvoices");
        }

    }
}

TrugoAdmin/Views/Invoices/ApprovedInvoices.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.InvoiceResponseModel>
@{
    ViewBag.Title = "View all Invoices";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all Invoices
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Client</th>
                            <th>Amount</th>
                            <th>Discount</th>
                            <th>Due Date</th>
                            <th>Sale Price</th>
                            <th>Posted by</th>
                            <th>Status</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {

                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.InvoiceTitle</td>
                                        <td>@item.Client</td>
                                        <td>@item.Amount</td>
                                        <td>@item.DiscountRate</td>
                                        <td>@item.DueDate</td>
                                        <td>@item.SalePrice</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.AdminStatus</td>
                                        <td>@item.Verified</td>
                                        <td>




                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#decline_@item.Id"><i class="la la-leaf"></i>Decline Request</a>
                                                    <a href="#" class="dropdown-item"><i class="la la-leaf"></i>Detailed View</a>
                                                    <a href="#" class="dropdown-item"><i class="la la-leaf"></i>View Payments</a>
                                                </div>
                                            </div>


                                        </td>

                                    </tr>

                                    <div class="modal fade" id="decline_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("DeclineRequest", "Invoices", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="hidden" name="InvoiceId" value="@item.Id" />
                                                    <input type="hidden" name="Code" value="@item.InvoiceGuid" />
                                                    <input type="hidden" name="UserId" value="@item.ProfileId" />
                                                    <div class="modal-body">
                                                        <p>This will decline the selected invoice</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>
                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}

TrugoAdmin/Views/Invoices/GetAllInvoices.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.InvoiceResponseModel>
@{
    ViewBag.Title = "View all Invoices";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all Invoices
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Client</th>
                            <th>Amount</th>
                            <th>Discount</th>
                            <th>Due Date</th>
                            <th>Sale Price</th>
                            <th>Posted by</th>
                            <th>Status</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {

                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.InvoiceTitle</td>
                                        <td>@item.Client</td>
                                        <td>@item.Amount</td>
                                        <td>@item.DiscountRate</td>
                                        <td>@item.DueDate</td>
                                        <td>@item.SalePrice</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.AdminStatus</td>
                                        <td>@item.Verified</td>
                                        <td>


                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#approve_@item.Id"><i class="la la-edit"></i>Approve Request</a>
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#decline_@item.Id"><i class="la la-leaf"></i>Decline Request</a>
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#verify_@item.Id"><i class="la la-leaf"></i>Verify Request</a>
                                                    <a href="http://apptest.trugo.co/MarketPlace/ViewInvoice?invoiceid=@item.Id&code=@item.InvoiceGuid" class="dropdown-item"><i class="la la-leaf"></i>Detailed View</a>
                                                    <a href="#" class="dropdown-item"><i class="la la-leaf"></i>View Payments</a>
                                                </div>
                                            </div>


                                        </td>

                                    </tr>

                                    <div class="modal fade" id="approve_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Approve User</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("ApproveRequest", "Invoices", FormMethod.Post))
                                                {
                                                    <div class="modal-body">

                                                        @Html.AntiForgeryToken()
                                                        <input type="hidden" name="InvoiceId" value="@item.Id" />
                                                        <input type="hidden" name="Code" value="@item.InvoiceGuid" />
                                                        <input type="hidden" name="UserId" value="@item.ProfileId" />

                                                        <h6>
                                                            This will approve the selected invoice request
                                                        </h6>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Approve</button>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>


                                    <div class="modal fade" id="decline_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("DeclineRequest", "Invoices", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="hidden" name="InvoiceId" value="@item.Id" />
                                                    <input type="hidden" name="Code" value="@item.InvoiceGuid" />
                                                    <input type="hidden" name="UserId" value="@item.ProfileId" />
                                                    <div class="modal-body">
                                                        <p>This will decline the selected invoice</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal fade" id="verify_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("VerifyRequest", "Invoices", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="hidden" name="InvoiceId" value="@item.Id" />
                                                    <input type="hidden" name="Code" value="@item.InvoiceGuid" />
                                                    <input type="hidden" name="UserId" value="@item.ProfileId" />
                                                    <div class="modal-body">
                                                        <p>This will verify the selected invoice request</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>

                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}

TrugoAdmin/Views/Invoices/VerifiedInvoices.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.InvoiceResponseModel>
@{
    ViewBag.Title = "Viewusers";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all users
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Client</th>
                            <th>Amount</th>
                            <th>Discount</th>
                            <th>Due Date</th>
                            <th>Sale Price</th>
                            <th>Posted by</th>
                            <th>Status</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {

                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.InvoiceTitle</td>
                                        <td>@item.Client</td>
                                        <td>@item.Amount</td>
                                        <td>@item.DiscountRate</td>
                                        <td>@item.DueDate</td>
                                        <td>@item.SalePrice</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.AdminStatus</td>
                                        <td>@item.Verified</td>
                                        <td>



                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#revoke_@item.Id"><i class="la la-edit"></i>Revoke</a>

                                                </div>
                                            </div>


                                        </td>

                                    </tr>

                                    <div class="modal fade" id="revoke_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("RevokeVerifiedRequest", "Invoices", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="hidden" name="Userid" value="@item.Profile.UserId" />
                                                    <input type="hidden" name="Invoiceid" value="@item.Id" />
                                                    <input type="hidden" name="Code" value="@item.InvoiceGuid" />

                                                    <div class="modal-body">
                                                        <p>
                                                            This will revoke the selected verified invoice request
                                                        </p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>

                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}