TrugoAdmin/Controllers/WithdrawController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrugoAdmin.Models.DalClasses;
using TruGoClassLibrary.RequestModels;

namespace TrugoAdmin.Controllers
{
    public class WithdrawController : Controller
    {
        private WithdrawalRequestClass _withdrawalRequestClass;

        public WithdrawalRequestClass WithdrawalRequestClass
        {
            get
            {
                return new WithdrawalRequestClass();
            }

            set
            {
                _withdrawalRequestClass = value;
            }
        }

        public WithdrawController()
        {

        }
        public WithdrawController(WithdrawalRequestClass withdrawalRequestClass)
        {
            WithdrawalRequestClass = withdrawalRequestClass;
        }



        // GET: Withdraw
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetallRequests()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = WithdrawalRequestClass.GetAllRequest();

            return View(requests);
        }

        public ActionResult GetVerifiedRequests()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = WithdrawalRequestClass.GetVerifiedRequests();

            return View(requests);
        }

        public ActionResult GetApprovedRequests()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = WithdrawalRequestClass.GetApprovedRequests();

            return View(requests);
        }

        public ActionResult GetPendingRequests()
        {
            if (Session["msg"] != null)
            {
                ViewBag.msg = Session["msg"].ToString();
                Session.Remove("msg");
            }
            else { }

            var requests = WithdrawalRequestClass.GetPendingRequests();

            return View(requests);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApproveRequest(CreditLibraryRequestModel model)
        {
            var status = WithdrawalRequestClass.ApproveRequest(model);

            if (status)
            {
                Session["msg"] = "Withdrawal request approved";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("GetallRequests");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VerifyRequest(CreditLibraryRequestModel model)
        {
            var status = WithdrawalRequestClass.VerifyRequest(model);

            if (status)
            {
                Session["msg"] = "Withdrawal request verified";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("GetVerifiedRequests");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeclineRequest(CreditLibraryRequestModel model)
        {
            var status = WithdrawalRequestClass.DeclineRequest(model);

            if (status)
            {
                Session["msg"] = "Withdrawal request declined";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("GetallRequests");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RevokeVerifiedRequest(CreditLibraryRequestModel model)
        {
            var status = WithdrawalRequestClass.RevokeVerifiedRequest(model);

            if (status)
            {
                Session["msg"] = "Withdrawal request revoked";
            }
            else
            {
                Session["msg"] = "An error occured";
            }

            return RedirectToAction("GetallRequests");
        }
    }
}

TrugoAdmin/Views/Withdraw/GetApprovedRequests.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.WithdrawCreditResponse>
@{
    ViewBag.Title = "Viewusers";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all users
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date Requested</th>
                            <th>Email Address</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Date Estimated</th>
                            <th>Amount Requested</th>
                            <th>Total Credit</th>
                            <th>Approved</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {
                                /**/
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.Profile.FirstName</td>
                                        <td>@item.Profile.LastName</td>
                                        <td>@item.Date_Estimate</td>
                                        <td>@item.Amount</td>
                                        <td>@item.Profile.TotalCredit</td>

                                        <td>@item.Status</td>
                                        <td>@item.Verified</td>

                                        <td>



                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#decline_@item.Id"><i class="la la-leaf"></i>Decline Request</a>
                                                </div>
                                            </div>


                                        </td>

                                    </tr>

                                    <div class="modal fade" id="decline_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("DeclineRequest", "Withdraw", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="hidden" name="Userid" value="@item.Profile.UserId" />
                                                    <input type="hidden" name="Id" value="@item.Id" />
                                                    <input type="hidden" name="CreditAmount" value="@item.Amount" />

                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="message-text" class="form-control-label">Additional Response:</label>
                                                            <textarea class="form-control" name="additionalmessage" id="message-text"></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>

                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}

TrugoAdmin/Views/Withdraw/GetPendingRequests.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.WithdrawCreditResponse>
@{
    ViewBag.Title = "Viewusers";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all users
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date Requested</th>
                            <th>Email Address</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Date Estimated</th>
                            <th>Amount Requested</th>
                            <th>Totall Credit</th>
                            <th>Approved</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {
                                /**/
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.Profile.FirstName</td>
                                        <td>@item.Profile.LastName</td>
                                        <td>@item.Date_Estimate</td>
                                        <td>@item.Amount</td>
                                        <td>@item.Profile.TotalCredit</td>
                                        <td>@item.Status</td>
                                        <td>@item.Verified</td>

                                        <td>



                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#approve_@item.Id"><i class="la la-edit"></i>Approve Request</a>

                                                </div>
                                            </div>


                                        </td>

                                    </tr>

                                    <div class="modal fade" id="approve_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Approve User</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("ApproveRequest", "Withdraw", FormMethod.Post))
                                                {
                                                    <div class="modal-body">
                                                        <div class="modal-body">

                                                            @Html.AntiForgeryToken()
                                                            <input type="hidden" name="Userid" value="@item.Profile.UserId" />
                                                            <input type="hidden" name="Id" value="@item.Id" />
                                                            <input type="hidden" name="CreditAmount" value="@item.Amount" />

                                                            <h6>
                                                                This will approve the selected withdrawal request
                                                            </h6>


                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Approve</button>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>

                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}

TrugoAdmin/Views/Withdraw/GetVerifiedRequests.cshtml
@model IEnumerable<TruGoClassLibrary.ResponseClass.WithdrawCreditResponse>
@{
    ViewBag.Title = "Viewusers";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/Content/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <input type="hidden" id="msg" value="@ViewBag.msg" />
    <div class="m-content">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            View all users
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                </div>
            </div>
            <div class="m-portlet__body">

                <table id="m_table_1" class="table table-striped- table-bordered table-hover table-checkable" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Date Requested</th>
                            <th>Email Address</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Date Estimated</th>
                            <th>Amount Requested</th>
                            <th>Totall Credit</th>
                            <th>Approved</th>
                            <th>Verified</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model == null)
                            {
                                /**/
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.Date_Created</td>
                                        <td>@item.Profile.EmailAddress</td>
                                        <td>@item.Profile.FirstName</td>
                                        <td>@item.Profile.LastName</td>
                                        <td>@item.Date_Estimate</td>
                                        <td>@item.Amount</td>
                                        <td>@item.Profile.TotalCredit</td>
                                        <td>@item.Status</td>
                                        <td>@item.Verified</td>

                                        <td>


                                            <div class="dropdown">
                                                <a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="la la-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-187px, -57px, 0px);">
                                                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#revoke_@item.Id"><i class="la la-edit"></i>Revoke</a>
                                                </div>
                                            </div>
                                        </td>

                                    </tr>

                                    <div class="modal fade" id="revoke_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Revoke Verification</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                @using (Html.BeginForm("RevokeVerifiedRequest", "Withdraw", FormMethod.Post))
                                                {
                                                    <div class="modal-body">
                                                        <div class="modal-body">

                                                            @Html.AntiForgeryToken()
                                                            <input type="hidden" name="Userid" value="@item.Profile.UserId" />
                                                            <input type="hidden" name="Id" value="@item.Id" />
                                                            <input type="hidden" name="CreditAmount" value="@item.Amount" />

                                                            <h6>
                                                                This will revoke the selected verified withdrawal request
                                                            </h6>


                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Revoke</button>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>

                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/Scripts/Viewusers.js"></script>
}